export const PRODUCT_CATEGORIES = [
  {
    name: 'Hogar',
    imgUrl: '/static/utiles del hogar.webp',
    subcategories: [
      'Limpieza y Mantenimiento del Hogar',
      'Cocina y Comedor',
      'Organización y Almacenamiento',
      'Baño',
      'Decoración del Hogar',
      'Textiles para el Hogar',
      'Muebles para el Hogar',
      'Iluminación',
      'Otros artículos para el Hogar',
    ],
  },
  {
    name: 'Comida y Bebida',
    imgUrl: '/static/Comida y Bebida.webp',
    subcategories: [
      'Carnes y Pescados',
      'Embutidos',
      'Enlatados y Conservas',
      'Congelados',
      'Cereales, Granos y Pastas',
      'Dulces y Snacks',
      'Preparaciones Instantáneas',
      'Café e Infusiones',
      'Panadería y Repostería',
      'Lácteos y Derivados',
      'Productos del Agro',
      'Salsas, Aderezos y Vinagretas',
      'Aceites, Endulzantes y Condimentos',
      'Jugos, Refrescos y Otros',
      'Bebidas Alcohólicas',
      'Otros Alimentos y Bebidas',
    ],
  },
  {
    name: 'Ropa y Calzado',
    imgUrl: '/static/Ropa y Calzado.webp',
    subcategories: [
      'Ropa de Hombre',
      'Ropa de Mujer',
      'Ropa Niños/as',
      'Calzado Niños/as',
      'Calzado Mujer',
      'Calzado Hombre',
      'Trajes de Baño',
      'Abrigos, Sudaderas',
      'Disfraces',
      'Ropa Interior',
      'Pijamas',
      'Otra Ropa y Calzado',
    ],
  },
  {
    name: 'Accesorios',
    imgUrl: '/static/Accesorios.webp',
    subcategories: [
      'Bolsos para Mujer',
      'Bolsos para Hombres',
      'Accesorios para el Cabello',
      'Gafas',
      'Gorras y Sombreros',
      'Mochilas y Maletas',
      'LLaveros',
      'Billeteras y Monederos',
      'Cinturones y Tirantes',
      'Bufandas y Pañuelos',
      'Otros Accesorios',
    ],
  },
  {
    name: 'Joyería y Relojería',
    imgUrl: '/static/Accesorios.webp',
    subcategories: [
      'Pulseras',
      'Collares',
      'Anillos',
      'Piercings',
      'Relojes',
      'Broches',
      'Tobilleras',
      'Pendientes',
      'Otros Artículos de Joyería',
    ],
  },
  {
    name: 'Productos para Bebés',
    imgUrl: '/static/Productos para niños.webp',
    subcategories: [
      'Juguetes para Bebés',
      'Ropa para Bebés',
      'Calzado para Bebés',
      'Muebles Infantiles',
      'Accesorios para Bebés',
      'Cuidados Básicos',
      'Higiene y Cuidado para Bebés',
      'Alimentación Infantil',
      'Otros productos para Bebés',
    ],
  },
  {
    name: 'Animales y Mascotas',
    imgUrl: '/static/Productos para mascotas.webp',
    subcategories: [
      'Alimentos para Mascotas',
      'Juguetes para Mascotas',
      'Aseo y Estética',
      'Ropa y Accesorios para Mascotas',
      'Medicamentos para Mascotas',
      'Adopción y Venta de Mascotas',
      'Camas, Casas y Transportadoras',
      'Comederos y Bebederos',
      'Peceras y Jaulas',
      'Otros productos para Animales y Mascotas',
    ],
  },
  {
    name: 'Belleza y Cuidado Personal',
    imgUrl: '/static/Belleza y cuidado personal.webp',
    subcategories: [
      'Maquillaje y Accesorios',
      'Cuidado de la Piel',
      'Cuidado del Cabello',
      'Perfumes',
      'Accesorios para el Cabello',
      'Manicura y Pedicura',
      'Aseo e Higiene Personal',
      'Otros productos de Belleza y Cuidado Personal',
    ],
  },
  {
    name: 'Salud y Bienestar',
    imgUrl: '/static/medicinas.webp',
    subcategories: [
      'Vitaminas',
      'Suplementos',
      'Analgésicos y antiflamatorios',
      'Anticonceptivos',
      'Antibióticos',
      'Medicamentos digestivos',
      'Antialérgicos, tos y resfriado',
      'Equipos de Salud',
      'Cremas y ungüentos',
      'Otros medicamentos',
      'Otros artículos de Salud y Bienestar',
    ],
  },
  {
    name: 'Tecnología y Electrónica',
    imgUrl: '/static/Tecnologia y Electronica.webp',
    subcategories: [
      'Celulares y Accesorios',
      'Laptop, Computadoras y Componentes',
      'Equipos de música y audio',
      'Accesorios de  Tecnología',
      'TV y accesorios',
      'Redes y Conectividad',
      'Energía Portátil y Respaldo',
      'Audio, Vídeo y Fotografía',
      'Gaming y Consolas',
      'Seguridad y Vigilancia',
      'Otros Equipos Eléctricos y Tecnológicos',
    ],
  },
  {
    name: 'Electrodomésticos',
    imgUrl: '/static/Electrodomésticos.jpg',
    subcategories: [
      'Equipos de Cocina',
      'Equipos para el Hogar',
      'Climatización',
      'Refrigeración',
      'Otros equipos eléctricos',
    ],
  },
  {
    name: 'Vehículos y Piezas',
    imgUrl: '/static/Vehiculos y piezas.webp',
    subcategories: [
      'Autos, Piezas y Accesorios',
      'Motos, Piezas y Accesorios',
      'Bicicletas, Piezas y Accesorios',
      'Motos Eléctricas, Piezas y Accesorios',
      'Neumáticos, Aceites y Lubricantes',
      'Accesorios para Vehículos',
      'Piezas Variadas',
      'Otros Artículos para Vehículos',
    ],
  },
  {
    name: 'Ferretería y Construcción',
    imgUrl: '/static/Ferretería.webp',
    subcategories: [
      'Herramientas Manuales',
      'Herramientas Eléctricas',
      'Cajas de Herramientas y Almacenamiento',
      'Adhesivos, Cintas y Selladores',
      'Piezas y Respuestos',
      'Pinturas y Accesorios',
      'Plomería',
      'Electricidad',
      'Cerrajería y Seguridad',
      'Cemento, Bloque y Materiales de Albañilería',
      'Pisos y Revestimientos',
      'Puertas y Ventanas',
      'Maquinaria de Construcción',
      'Equipos de Seguridad',
      'Otros Artículos para la Construcción',
      'Artículos varios de Ferretería',
    ],
  },
  {
    name: 'Deporte y Fitness',
    imgUrl: '/static/Implementos Deportivos.jpg',
    subcategories: [
      'Ropa Deportiva',
      'Calzado Deportivo',
      'Equipos Deportivos',
      'Accesorios Deportivos',
      'Suplementos Deportivos',
      'Otros Artículos Deportivos',
    ],
  },
  {
    name: 'Entretenimiento',
    imgUrl: '/static/Entretenimiento.jpg',
    subcategories: [
      'Juegos',
      'Música',
      'Películas',
      'Libros',
      'Consola y PC',
      'Juguetes',
    ],
  },
  {
    name: 'Decoración de Eventos',
    imgUrl: '/static/Decoración.jpg',
    subcategories: [
      'Accesorios para Eventos',
      'Decoración para Bodas',
      'Decoración y Productos para Cumpleaños',
      'Decoración para Graduaciones',
      'Decoración navideña',
      'Decoración para Halloween',
      'Velas, Globos y Accesorios',
      'Centro de Mesa y Arreglos',
      'Cajas, Bolsas y Envoltorios para regalos',
      'Otros Artículos para Decorar Eventos',
    ],
  },
  {
    name: 'Plantas',
    imgUrl: '/static/Plantas.jpg',
    subcategories: [
      'Plantas de Interior',
      'Plantas de Exterior',
      'Herramientas de Jardinería',
      'Plantas Medicinales y Aromáticas',
      'Cactus',
      'Suculentas',
      'Bonsáis',
      'Macetas y Accesorios',
    ],
  },
  {
    name: 'Productos Escolares y de Oficina',
    imgUrl: '/static/Productos de oficina.webp',
    subcategories: [
      'Cintas, Adhesivos y Pegamentos',
      'Materiales de dibujo y arte',
      'Cartulina, Papeles y Agendas',
      'Mochilas, estuches, organizadores',
      'Libros y Libretas',
      'Equipamiento Escolar',
      'Equipamiento para Oficinas',
      'Otros artículos escolares y de oficina',
    ],
  },
  {
    name: 'Inmuebles',
    imgUrl: '/static/Vivienda.webp',
    subcategories: ['Casas', 'Apartamentos', 'Terrenos', 'Locales', 'Alquiler'],
  },
  {
    name: 'Productos para Adultos',
    imgUrl: '/static/Productos para Adultos.webp',
    subcategories: [
      'Juguetes Sexuales',
      'Ropa Erótica',
      'Lubricantes',
      'Accesorios y Complementos',
      'Condones',
      'Otros Productos para Adultos',
    ],
  },
  {
    name: 'Venta de Divisas',
    imgUrl: '/static/ventas de divisa.webp',
    subcategories: ['USD', 'EURO', 'MLC', 'CANADIENSE', 'Remesas'],
  },
] as const;
