export const PRODUCT_CATEGORIES = [
  {
    name: 'Hogar',
    imgUrl: '/static/utiles del hogar.webp',
    subcategories: [
      'Limpieza y Aseo del Hogar',
      'Útiles de Cocina',
      'Organización y Decoración',
      'Otros artículos para el hogar',
    ],
  },
  {
    name: 'Comida y Bebida',
    imgUrl: '/static/Comida y Bebida.webp',
    subcategories: [
      'Carnes y Pescados',
      'Embutidos',
      'Enlatados y Conservas',
      'Congelados',
      'Cereales, Granos y Pastas',
      'Dulces y Snacks',
      'Preparaciones instantáneas',
      'Café e Infusiones',
      'Panadería, Pastelería',
      'Lácteos y derivados',
      'Productos del Agro',
      'Salsas y aderezos',
      'Aceites, Endulzantes y condimentos',
      'Jugos, Refrescos y Otros',
      'Bebidas Alcohólicas',
      'Otros alimentos y bebidas',
    ],
  },
  {
    name: 'Ropa y Calzado',
    imgUrl: '/static/Ropa y Calzado.webp',
    subcategories: [
      'Ropa de Hombre',
      'Ropa de Mujer',
      'Ropa Niños/as',
      'Calzado Niños/as',
      'Calzado Mujer',
      'Calzado Hombre',
      'Trajes de Baño',
      'Abrigos, Sudaderas',
      'Disfraces',
      'Ropa Interior',
      'Pijamas',
      'Otra Ropa y Calzado',
    ],
  },
  {
    name: 'Accesorios',
    imgUrl: '/static/Accesorios.webp',
    subcategories: [
      'Bolsos para Mujer',
      'Bolsos para Hombres',
      'Pulseras',
      'Collares',
      'Anillos',
      'Piercings',
      'Pendientes',
      'Gafas',
      'Sombreros',
      'Mochilas y Maletas',
      'LLaveros',
      'Otros Accesorios',
    ],
  },
  {
    name: 'Productos para Bebés',
    imgUrl: '/static/Productos para niños.webp',
    subcategories: [
      'Juguetes',
      'Ropa y Calzado para Bebés',
      'Muebles Infantiles',
      'Accesorios para Bebés',
      'Cuidados Básicos',
      'Artículos de Higiene y baño del bebé',
      'Otros productos para bebés',
    ],
  },
  {
    name: 'Animales y Mascotas',
    imgUrl: '/static/Productos para mascotas.webp',
    subcategories: [
      'Alimentos para Mascotas',
      'Juguetes para Mascotas',
      'Aseo y Estética',
      'Ropa y Accesorios para Mascotas',
      'Medicamentos para Mascotas',
      'Mascotas',
      'Camas para Mascotas',
      'Comederos y Bebederos',
      'Otros productos para Animales y Mascotas',
    ],
  },
  {
    name: 'Belleza y Cuidado Personal',
    imgUrl: '/static/Belleza y cuidado personal.webp',
    subcategories: [
      'Maquillaje y Accesorios',
      'Cuidado de la Piel',
      'Cuidado del Cabello',
      'Perfumes',
      'Accesorios para el Cabello',
      'Manicura y Pedicura',
      'Aseo e Higiene Personal',
      'Otros productos de Belleza y Cuidado Personal',
    ],
  },
  {
    name: 'Salud y Bienestar',
    imgUrl: '/static/medicinas.webp',
    subcategories: [
      'Vitaminas',
      'Suplementos',
      'Equipos de Salud',
      'Analgésicos y antiflamatorios',
      'Anticonceptivos',
      'Antialérgicos, tos y resfriado',
      'Cremas',
      'Otros medicamentos',
      'Otros artículos de Salud y Bienestar',
    ],
  },
  {
    name: 'Tecnología y Electrónica',
    imgUrl: '/static/Tecnologia y Electronica.webp',
    subcategories: [
      'Celulares y Accesorios',
      'Computadoras, Piezas y Accesorios',
      'Equipos de música y audio',
      'Accesorios de Tecnología',
      'TV y accesorios',
      'Gaming y Consolas',
      'Otros Equipos Eléctricos y Tecnológicos',
    ],
  },
  {
    name: 'Electrodomésticos',
    imgUrl: '/static/Electrodomésticos.jpg',
    subcategories: [
      'Equipos de Cocina',
      'Equipos para el Hogar',
      'Climatización',
      'Refrigeración',
      'Otros equipos eléctricos',
    ],
  },
  {
    name: 'Vehículos y Piezas',
    imgUrl: '/static/Vehiculos y piezas.webp',
    subcategories: [
      'Autos, Piezas y Accesorios',
      'Motos, Piezas y Accesorios',
      'Bicicletas, Piezas y Accesorios',
      'Accesorios para Vehículos',
      'Piezas Variadas',
    ],
  },
  {
    name: 'Ferretería',
    imgUrl: '/static/Ferretería.webp',
    subcategories: [
      'Herramientas Manuales',
      'Herramientas Eléctricas',
      'Adhesivos',
      'Piezas y Respuestos',
      'Pinturas',
      'Plomería',
      'Electricidad',
      'Artículos varios de Ferretería',
    ],
  },
  {
    name: 'Implementos Deportivos',
    imgUrl: '/static/Implementos Deportivos.jpg',
    subcategories: [
      'Ropa Deportiva',
      'Equipos Deportivos',
      'Accesorios Deportivos',
      'Suplementos',
      'Otros Implementos deportivos',
    ],
  },
  {
    name: 'Entretenimiento',
    imgUrl: '/static/Entretenimiento.jpg',
    subcategories: [
      'Juegos',
      'Música',
      'Películas',
      'Libros',
      'Consola y PC',
      'Juguetes',
    ],
  },
  {
    name: 'Decoración',
    imgUrl: '/static/Decoración.jpg',
    subcategories: [
      'Arte y Manualidades',
      'Accesorios para Eventos',
      'Decoración para Bodas',
      'Decoración y productos para Cumpleaños',
      'Velas y Accesorios',
      'Artículos para decorar eventos',
    ],
  },
  {
    name: 'Plantas',
    imgUrl: '/static/Plantas.jpg',
    subcategories: [
      'Plantas de Interior',
      'Plantas de Exterior',
      'Herramientas de Jardinería',
      'Plantas Medicinales y Aromáticas',
      'Cactus',
      'Suculentas',
      'Bonsáis',
      'Macetas y Accesorios',
    ],
  },
  {
    name: 'Productos Escolares y de Oficina',
    imgUrl: '/static/Productos de oficina.webp',
    subcategories: [
      'Cintas, Adhesivos y Sujetadores',
      'Materiales de dibujo y arte',
      'Cartulina, Papeles y Agendas',
      'Mochilas, estuches, organizadores',
      'Libros y Libretas',
      'Equipamiento Escolar',
      'Equipamiento para Oficinas',
      'Otros artículos escolares y de oficina',
    ],
  },
  {
    name: 'Inmuebles',
    imgUrl: '/static/Vivienda.webp',
    subcategories: ['Casas', 'Apartamentos', 'Terrenos', 'Locales', 'Alquiler'],
  },
  {
    name: 'Materiales para la Construcción',
    imgUrl: '/static/Materiales de la construccion.webp',
    subcategories: [
      'Herramientas de Construcción',
      'Componentes para el Mobiliario',
      'Maquinaria para la construcción',
      'Herramientas para la construcción',
      'Otros Artículos para la construcción',
    ],
  },
  {
    name: 'Productos para Adultos',
    imgUrl: '/static/Productos para Adultos.webp',
    subcategories: [
      'Juguetes Sexuales',
      'Ropa Erótica',
      'Lubricantes',
      'Accesorios',
      'Condones',
      'Otros Productos para Adultos',
    ],
  },
  {
    name: 'Venta de Divisas',
    imgUrl: '/static/ventas de divisa.webp',
    subcategories: ['USD', 'EURO', 'MLC', 'CANADIENSE', 'Remesas'],
  },
] as const;
